set(_CATKIN_CURRENT_PACKAGE "ebimu_odometry")
set(ebimu_odometry_VERSION "0.0.0")
set(ebimu_odometry_MAINTAINER "pdi <pdi@todo.todo>")
set(ebimu_odometry_PACKAGE_FORMAT "2")
set(ebimu_odometry_BUILD_DEPENDS "nav_msgs" "roscpp" "rospy" "std_msgs" "tf")
set(ebimu_odometry_BUILD_EXPORT_DEPENDS "nav_msgs" "roscpp" "rospy" "std_msgs" "tf")
set(ebimu_odometry_BUILDTOOL_DEPENDS "catkin")
set(ebimu_odometry_BUILDTOOL_EXPORT_DEPENDS )
set(ebimu_odometry_EXEC_DEPENDS "nav_msgs" "roscpp" "rospy" "std_msgs" "tf")
set(ebimu_odometry_RUN_DEPENDS "nav_msgs" "roscpp" "rospy" "std_msgs" "tf")
set(ebimu_odometry_TEST_DEPENDS )
set(ebimu_odometry_DOC_DEPENDS )
set(ebimu_odometry_URL_WEBSITE "")
set(ebimu_odometry_URL_BUGTRACKER "")
set(ebimu_odometry_URL_REPOSITORY "")
set(ebimu_odometry_DEPRECATED "")