set(_CATKIN_CURRENT_PACKAGE "kbcontrol")
set(kbcontrol_VERSION "0.0.0")
set(kbcontrol_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(kbcontrol_PACKAGE_FORMAT "2")
set(kbcontrol_BUILD_DEPENDS "roscpp" "rospy")
set(kbcontrol_BUILD_EXPORT_DEPENDS "roscpp" "rospy")
set(kbcontrol_BUILDTOOL_DEPENDS "catkin")
set(kbcontrol_BUILDTOOL_EXPORT_DEPENDS )
set(kbcontrol_EXEC_DEPENDS "roscpp" "rospy")
set(kbcontrol_RUN_DEPENDS "roscpp" "rospy")
set(kbcontrol_TEST_DEPENDS )
set(kbcontrol_DOC_DEPENDS )
set(kbcontrol_URL_WEBSITE "")
set(kbcontrol_URL_BUGTRACKER "")
set(kbcontrol_URL_REPOSITORY "")
set(kbcontrol_DEPRECATED "")